from flask import Flask, render_template, request
import json
from google.cloud import pubsub_v1

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/generate_event', methods = ['POST'])
def sendClicks():
    buttonID = request.form.get('button_id')
    
    # Handle the event generation logic with the button ID
    event_info = f"Event generated by button with ID: {buttonID}"
    
    return render_template('index.html', event_info=event_info)

def message_publisher(message):

    # Convert the message dictionary to a JSON string
    message_str = json.dumps(message)

    # Set up the Pub/Sub client and topic
    publisher = pubsub_v1.PublisherClient()
    topic_path = publisher.topic_path('business-deck', 'click-events-topic')
    
    # Publish the message to the topic
    future = publisher.publish(topic_path, message_str.encode('utf-8'))

def main(request):
    return app